GET http://localhost:4000/users

###

POST http://localhost:4000/users
Content-Type: application/json

{
    "username": "User1",
    "password": "password"  
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlcjEiLCJpYXQiOjE3NTQwOTU5MTAsImV4cCI6MTc1NDA5NjUxMH0.ph0KCi41Km_quEZquM6G3R2DTg-wWk4VZu_Eb84MMYk

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "username": "User1"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "User1",
    "password": "password"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlcjEiLCJpYXQiOjE3NTQwOTU5MTl9.YeCVTcHKs3BedwaJI9N9DMjVp3zhL1icXr57xXSi9XM"
}