name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or "master", if that's your main branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build React App
        working-directory: frontend
        run: npm run predeploy

      - name: Deploy to GitHub Pages
        run: |
          cd frontend
          npm run deploy
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
